# Generated by Django 3.2.25 on 2025-03-27 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_auto_20200514_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrixFactorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_factors', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('iterations', models.IntegerField()),
                ('regularization', models.FloatField()),
            ],
            options={
                'db_table': 'MatrixFactorization',
            },
        ),
        migrations.CreateModel(
            name='RecommendationCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_movies', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.user')),
            ],
            options={
                'db_table': 'RecommendationCache',
            },
        ),
        migrations.CreateModel(
            name='UserFactors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factors', models.TextField()),
                ('mf_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.matrixfactorization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.user')),
            ],
            options={
                'db_table': 'UserFactors',
                'unique_together': {('user', 'mf_model')},
            },
        ),
        migrations.CreateModel(
            name='MovieFactors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factors', models.TextField()),
                ('mf_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.matrixfactorization')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
            ],
            options={
                'db_table': 'MovieFactors',
                'unique_together': {('movie', 'mf_model')},
            },
        ),
    ]
